### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xuanll** [xuanll/xMailList#1]
- [x] Download Unity windows version :tada: 
- [x] Download project from PC and run it :tada: 
- [x] Move all gameObject to the Scripts 🎉 
- [x] Write README for the current version :tada: 
- [x] Refactor the Project - new branch(fw) is needed :arrow_double_up: 
- [ ] Create new Issue - BUG
